# Generated by Django 6.0 on 2025-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='final_files/'),
        ),
    ]
