# Generated by Django 6.0 on 2025-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('fullstack', 'Full Stack Developer'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('mobile', 'Mobile Developer'), ('designer', 'UI/UX Designer'), ('editor', 'Video / Photo Editor')], max_length=50),
        ),
    ]
